### ISSUE TITLE
为什么1.2.2版本的NextId()返回值类型改为int64了？

### ISSUE THREAD

**Issue by liuxingke** [yitter/idgenerator-go#2]
为什么1.2.2版本的NextId()返回值类型改为int64了？上一个版本是uint64，生成的id不应该有负数吧？

**Comment by houseme** [comment]
@yitter

**Comment by yitter** [comment]
主要是为了跟其它语言保持逻辑一致。如果你采用系统默认配置，放心的用吧，1万年都用不完。 
即便你增加参数值，一般也是几百年用不完。

**Comment by stephaneThannio** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Erikevin, @ruipengliu, @zhiweiofli, @liuxiong332, @simon639, @leigaoxing, @Hyiker, @yellowlooks, @wallisyoung, @jordan-johnson-sq, @lf2net089, @jiahuanyu, @theleveragedguess, @Mindzy, @GinChow, @cybercarrot, @bingn, @xuongmaydosi, @Yousefcheng, @deepinwine, @Shiliuang, @WenRichard, @LIUMINGLAN, @liusimonpku, @FlyWay-one, @vzii, @KuJyoAi, @lasting-yang, @miku8miku, @iderekliu, @vlike, @dataCreateMao, @BigtoC, @wwwj27, @Stephen-Xu, @MarineHuang, @CodingSunhj, @leeyo, @nickostendorf, @junessi, @andmeics, @ikunpy, @LongquanLiu, @ourines, @Kennyhrk, @findfz, @wkk88992, @watsonzh, @zhonghua-han, @sunqiang-leo

**Comment by andutzu7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
abyssimth, @ethicnology, @zsjleo, @ERIONKE01, @reyesvicente, @cdevry, @LearnerWu, @Atlasoin, @i4irsh, @manero6, @Elefyqyl, @codingIsCrazy, @laplaceliu, @ellolee, @heiheiheiheiheihei, @baajarmeh, @AyabongaQwabi, @AlexandriaLittle, @Javierchast, @AlirezaSafari7, @latenightz, @luizferrbarbosa, @ANTEVETY, @itsazzad, @Simon-CHOU, @jieruypoe, @apoplepsja, @Yz4230, @mo1ny, @TomLisankie, @cbarraco, @LVtomatoJ, @mitiko, @trailblazingfive, @villivateur, @dreczkaa, @Yinr, @Minamiyama, @RXWatcher, @maddefientist, @Flouse, @t0ster30, @TrevorBagels, @RadonX, @StrawDogs, @wnma3mz, @NullpointerWorks, @gnknithin, @MadReza, @Dont-Copy-That-Floppy
